#!/bin/bash

# Read fixed parameters that are always sent by irace
CONFIG_ID=$1
INSTANCE_ID=$2
SEED=$3
INSTANCE=$4

# Shift the arguments to process only those for ALNS
shift 4

# Initialize variables
MAX_ITER="10000"
COOLING=""
DESTROY=""
SHAW_DIST=""
SHAW_TIME=""
SHAW_DEMAND=""
WORST_REMOVAL_POWER=""
SIGMA1=""
SIGMA2=""
SIGMA3=""
REACTION_FACTOR=""

# Read the parameters generated by irace
while [[ "$#" -gt 0 ]]; do
    case $1 in
        --coolingRate) COOLING="$2"; shift 2 ;;
        --destroyFraction) DESTROY="$2"; shift 2 ;;
        --shawDistWeight) SHAW_DIST="$2"; shift 2 ;;
        --shawTimeWeight) SHAW_TIME="$2"; shift 2 ;;
        --shawDemandWeight) SHAW_DEMAND="$2"; shift 2 ;;
        --worstRemovalPower) WORST_REMOVAL_POWER="$2"; shift 2 ;;
        --sigma1) SIGMA1="$2"; shift 2 ;;
        --sigma2) SIGMA2="$2"; shift 2 ;;
        --sigma3) SIGMA3="$2"; shift 2 ;;
        --reactionFactor) REACTION_FACTOR="$2"; shift 2 ;;
        *) shift ;; # Ignore unknown parameters
    esac
done

# Run solver with the provided parameters
../build/cpp/core/mddarp_run \
    -i "$INSTANCE" \
    -m ALNS \
    -s "$SEED" \
    --NR \
    --alnsParams "$MAX_ITER" "$COOLING" "$DESTROY" "$WORST_REMOVAL_POWER" "$SHAW_DIST" "$SHAW_TIME" "$SHAW_DEMAND" "$SIGMA1" "$SIGMA2" "$SIGMA3" "$REACTION_FACTOR"